image: node:18

stages:
  - test

variables:
  CHROME_BIN: "/usr/bin/google-chrome"
  NODE_ENV: "test"

before_script:
  - apt-get update
  - apt-get install -y wget curl unzip openjdk-11-jre xvfb libxi6 libgconf-2-4
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - dpkg -i google-chrome*.deb || apt-get -fy install
  - npm install
  - npm install -g allure-commandline

test_ui:
  stage: test
  script:
    - echo "Ejecutando pruebas con Allure..."
    - xvfb-run --auto-servernum npm run test
    - allure generate allure-results --clean -o allure-report
  artifacts:
    when: always
    paths:
      - allure-report/
    expire_in: 1 week