image: node:18

stages:
  - test

variables:
  CHROME_BIN: "/usr/bin/google-chrome"
  NODE_ENV: "test"

before_script:
  - apt-get update
  - apt-get install -y wget curl unzip xvfb libxi6 libgconf-2-4
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - dpkg -i google-chrome*.deb || apt-get -fy install
  - npm install

test_ui:
  stage: test
  script:
    - echo "Running Selenium + Mocha tests"
    - xvfb-run --auto-servernum npm test