image: node:18

stages:
  - test

variables:
  BROWSERSTACK_USERNAME: "isaacbarraza_2O0N9C7Q"
  BROWSERSTACK_ACCESS_KEY: "oVZijprYgj3jyvxtWgsk"

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

test_regression:
  stage: test
  script:
    - npm run test:regression
    - npm run allure:generate
  artifacts:
    when: always
    paths:
      - allure-report
    expire_in: 1 week
